server.port=10096

application.name=eeutilpdfatools

server.servlet.context-path=/eeutilpdfatools

logging.config=file:${eeutil-pdfa-tools.config.path}/logback.xml


logging:
  level:
    org.jodconverter: infoserver.port=10918

application.name=eeutilpdfatools

server.servlet.context-path=/eeutilpdfatools

logging.config=file:${eeutil-pdfa-tools.config.path}/logback.xml


logging:
  level:
    org.jodconverter: info